export * from './format'
export * from './links'
export * from './ui'

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const SHORT_TOKEN_REGEX = /^[A-Za-z0-9]{8,14}$/

export function isValidUUID(value: string): boolean {
  return UUID_REGEX.test(value)
}

// Confirmation/tracking route params: accepts the short tokens generated by
// lib/tokens.ts going forward, and the long-form UUIDs already sent out on
// links created before that change.
export function isValidToken(value: string): boolean {
  return isValidUUID(value) || SHORT_TOKEN_REGEX.test(value)
}

// Calling codes normalizePhone recognises as "this number already has a country code,
// leave it alone." Kept in sync with the dialling codes offered in components/PhoneInput.tsx
// (that file owns the picker UI; this is just the numbers-only list the server-safe
// normalizer below needs). Sorted longest-first so a 3-digit code like 965 is checked
// before a 1-digit code like 1 that would otherwise never get a chance to match.
const RECOGNIZED_COUNTRY_CODES = [
  '965', '966', '971', '973', '974', '968', '962', '961', '964', '963', '967', '880', '977',
  '20', '63', '94', '62', '91', '92', '44', '1',
].sort((a, b) => b.length - a.length)

// Digits-only, consistently prefixed with the Kuwait country code (965) — but only when the
// input actually looks like a bare local Kuwait number. Previously this did a blind
// `.replace(/^(?!965)/, '965')`, which mangled anything that already carried a country code:
// a leading international "00" survived the digit-strip (00965... -> 9650096...) and a
// non-Kuwait code got 965 glued on front (Saudi +96650... -> 9659665...). Now: strip a
// leading "00" or "+" first, and only prepend 965 when what's left has no recognisable
// country-code prefix and is the right length for a bare local Kuwait number (8 digits).
export function normalizePhone(phone: string): string {
  let digits = phone.replace(/\D/g, '')
  if (digits.startsWith('00')) digits = digits.slice(2)

  // Check length first: a bare local Kuwait number is always 8 digits, even if those
  // digits happen to start with another country's calling code (e.g. 965's mobile
  // numbers commonly start with 9, colliding with '91'/'94'/'92' etc. below).
  if (digits.length === 8) return `965${digits}`
  if (RECOGNIZED_COUNTRY_CODES.some(code => digits.startsWith(code))) return digits
  return digits
}

// Local (not UTC) YYYY-MM-DD for use in downloaded filenames.
export function filenameDate(date: Date = new Date()): string {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

// Standard Levenshtein (edit-distance) DP implementation — no external dependency.
export function levenshteinDistance(a: string, b: string): number {
  const m = a.length
  const n = b.length
  if (m === 0) return n
  if (n === 0) return m

  const prev = new Array(n + 1)
  const curr = new Array(n + 1)
  for (let j = 0; j <= n; j++) prev[j] = j

  for (let i = 1; i <= m; i++) {
    curr[0] = i
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1
      curr[j] = Math.min(
        prev[j] + 1,      // deletion
        curr[j - 1] + 1,  // insertion
        prev[j - 1] + cost // substitution
      )
    }
    for (let j = 0; j <= n; j++) prev[j] = curr[j]
  }

  return prev[n]
}
